name: Daily Paper Update

on:
  # 매일 자정(UTC 0시)에 자동 실행
  schedule:
    - cron: '0 22 * * *'
  
  # 수동 실행 가능
  workflow_dispatch:

# 파일 커밋을 위한 권한 설정
permissions:
  contents: write

jobs:
  update-paper:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # 2. Python 3.10 설치
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      # 3. 필요한 라이브러리 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
# 4. 위에서 만든 Python 스크립트를 실행합니다.
      - name: Run update script
        run: python ./update_papers.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      # 5. [중요!] 스크립트 실행으로 변경된 파일들을 Git에 커밋하고 푸시합니다.
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # 아카이브 파일과 오늘의 논문 파일(카테고리별 네임스페이스) 추가
          git add _data/**/*.yml
          
          # 변경 사항이 있을 때만 커밋합니다
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update: Daily paper" && git push)
