name: Daily Paper Update

on:
  # 매일 자정(UTC 0시)에 자동 실행
  schedule:
    - cron: '0 0 * * *'
  
  # 수동 실행 가능
  workflow_dispatch:

# 파일 커밋을 위한 권한 설정
permissions:
  contents: write

jobs:
  update-paper:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # 2. Python 3.10 설치
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      # 3. 필요한 라이브러리 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. update_papers.py 스크립트 실행
      - name: Run update script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python update_papers.py
      
      # 5. 변경사항 커밋 및 푸시
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add _data/
          git diff --staged --quiet || git commit -m "Auto-update: Daily paper"
          git push

